# Generated by Django 5.2.3 on 2025-06-30 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('emotion', models.CharField(max_length=50)),
                ('confidence', models.FloatField()),
                ('text', models.TextField()),
                ('source', models.CharField(max_length=100)),
                ('equity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shadow_app.equity')),
            ],
        ),
        migrations.AddField(
            model_name='equity',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shadow_app.exchange'),
        ),
        migrations.CreateModel(
            name='ShadowPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField()),
                ('constraint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shadow_app.constraint')),
                ('equity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shadow_app.equity')),
            ],
        ),
    ]
